apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: skullgnammer/catalog-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "300M"
          limits:
            cpu: "800m"
            memory: "700M"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-service
spec:
  selector:
    app: catalog-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080