spring:
  artemis:
    mode: native
    host: 127.0.0.1
    port: 61616
    user: admin
    password: admin
  application:
    name: catalog-service

logging:
  level:
    "[com.netflix.discovery]": OFF

server:
  port: 8082
