spring:
  application:
    name: catalog-service

server:
  port: 8080

resources:
  movie-resource: http://movie-resource-service:8080
  rating-resource: http://rating-resource-service:8080
  jwt-resource: http://jwt-resource-service:8080
