server:
  port: 8780

logging.level.com.example: TRACE

resources:
  movie-resource: http://localhost:8782
  rating-resource: http://localhost:8784
  jwt-resource: http://localhost:8764

spring:
  artemis:
    broker-url: 127.0.0.1:61616
    user: admin
    password: admin
