server:
  port: 8780

com.example:
  movie-resource:
    location: http://localhost:8782
  rating-resource:
    location: http://localhost:8784
  jwt-resource:
    location: http://localhost:8764

spring:
  artemis:
    broker-url: 127.0.0.1:61616
    user: admin
    password: admin
