spring:
  application:
    name: catalog-service

server:
  port: 8080

com.example:
  movie-resource:
    location: http://movie-resource-service:8080
  rating-resource:
    location: http://rating-resource-service:8080
